version: '3'
volumes:
    mongodata:
      external: true
services:
    database:
        image: 'mongo'
        container_name: 'mongodb_container'
        environment: 
            - MONGO_INITDB_DATABASE=mydb
            - MONGO_INITDB_USERNAME=root
            - MONGO_INITDB_PASSWORD=root
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongodata:/data/db
        ports:
            - '27017-27019:27017-27019'